export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}): any {
  return (
    <html lang="en">
      <body>
        <p>Teste</p>
        {children}
      </body>
    </html>
  );
}
